language: node_js

node_js:
    - '8'

cache:
    directories:
        - "node_modules"

install:
    - wget https://github.com/gohugoio/hugo/releases/download/v0.29/hugo_0.29_Linux-64bit.tar.gz
    - tar -zxvf hugo_0.29_Linux-64bit.tar.gz
    - npm install

script:
    - npm run build
    - ./hugo

deploy:
    provider: pages
    skip_cleanup: true # Otherwise will delete files to upload!
    github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
    local_dir: public
    on:
        branch: source
    target_branch: master